"""Data models for the Customer Success Engine."""

from __future__ import annotations

import datetime
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional


class ChurnRisk(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class AlertType(str, Enum):
    HEALTH_DROP = "health_drop"
    RENEWAL_APPROACHING = "renewal_approaching"
    TICKET_SPIKE = "ticket_spike"
    NO_ENGAGEMENT = "no_engagement"


class AlertSeverity(str, Enum):
    INFO = "info"
    WARNING = "warning"
    CRITICAL = "critical"


@dataclass
class Customer:
    """Represents a customer account."""

    id: int
    name: str
    email: str
    plan: str
    mrr: float  # Monthly Recurring Revenue in USD
    contract_start: datetime.date
    contract_end: datetime.date
    nps_score: Optional[int] = None  # Net Promoter Score (-100 to 100)
    health_score: float = 0.0  # 0–100
    churn_risk: ChurnRisk = ChurnRisk.LOW
    created_at: datetime.datetime = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc)
    )
    updated_at: datetime.datetime = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc)
    )

    @property
    def days_until_renewal(self) -> int:
        today = datetime.date.today()
        return (self.contract_end - today).days

    @property
    def is_active(self) -> bool:
        return self.contract_end >= datetime.date.today()


@dataclass
class EngagementEvent:
    """Records a single customer engagement event."""

    id: int
    customer_id: int
    event_type: str  # e.g. "login", "feature_use", "support_ticket", "nps_response"
    value: float = 1.0  # numeric value (e.g. ticket count, feature score)
    occurred_at: datetime.datetime = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc)
    )
    notes: str = ""


@dataclass
class Alert:
    """An alert generated by the CS Engine for a customer."""

    id: int
    customer_id: int
    alert_type: AlertType
    severity: AlertSeverity
    message: str
    resolved: bool = False
    created_at: datetime.datetime = field(
        default_factory=lambda: datetime.datetime.now(datetime.timezone.utc)
    )
    resolved_at: Optional[datetime.datetime] = None


@dataclass
class Playbook:
    """A recommended action for a given risk level or alert type."""

    id: int
    name: str
    trigger_churn_risk: Optional[ChurnRisk]  # None = applies to all
    trigger_alert_type: Optional[AlertType]  # None = applies to all
    description: str
    action_steps: str  # newline-separated list of steps
